spring:
  application:
    name: flight-booking



  r2dbc:
    url: r2dbc:postgresql://localhost:5432/flightdb
    username: postgres
    password: W300430f


  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

server:
  error:
    include-stacktrace: never